pub enum CSS_A{
    AccentColor,
    AlignContent,
    AlignItems,
    AlignSelf,
    AlignTrack,
    All,
    Animation,
    AnimationComposition,
    AnimationDelay,
    AnimationDirection,
    AnimationDuration,
    AnimationFillMode,
    AnimationIterationCount,
    AnimationName,
    AnimationPlayState,
    AnimationTimeline,
    AnimationTimingFunction,
    Appearance,
    AccentOverride,
    AspectRatio,
}

