[package]
name = "css_parts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html_constant = { path = "../html_constant" }
css_constant = { path = "../css_constant" }