[package]
name = "title_base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html_constant = { path = "../../html_constant"}
html_tags = { path = "../../html_tags" }